version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.11-browsers
    working_directory: ~/repo
    filter:
      branches:
        only: 
          - dev
    steps:
      - checkout
      - run: yarn install