version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11-browsers
    steps:
      - checkout
      - run: echo "hellow"
  test:
    docker:
      - image: circleci/node:10.11-browsers
    steps:
      - checkout
      - run: echo "hellow"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build