# Project information
base_url: './'
site_name: Jian
site_description: 'A Vue Material Design Admin Template'
site_author: 'Micahel Wang'
site_url: 'https://vma.isocked.com'

# Repository


# Copyright
copyright: 'Copyright &copy; 2018 Michael Wang'

# Documentation and theme
# theme_dir: 'material'
# site_favicon: 'images/m.png'
theme:
  name: 'rtd-dropdown'

# Options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/tookit'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/michael-wang-22b23b66/'
  feature:
    tabs: true

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc(permalink=true)

# Google Analytics
google_analytics:
  - 'UA-69898504-1'
  - 'auto'

pages:
    - Home:
      - Getting Start: index.md
      - Components: components.md
    # Pages which are not visible from menu
# Plugin
plugins:
    - search
